### Base
GET http://localhost:8080/

### Swagger UI
GET http://localhost:8080/api-docs

### Get all contacts
GET http://localhost:8080/contacts

### Create contact (POST) - all fields required
POST http://localhost:8080/contacts
Content-Type: application/json

{
  
  "firstName": "Chidiebere",
  "lastName": "Anyalechi",
  "email": "chidiebere@updated.com",
  "favoriteColor": "Blue",
  "birthday": "1994-07-20"
}

### Get contact by id from POST response)
GET http://localhost:8080/contacts/68bc57dc92caf43538c1dc12

### Update contact (PUT) - must include all fields
PUT http://localhost:8080/contacts/68bc57dc92caf43538c1dc12
Content-Type: application/json

{
  "firstName": "Chidiebere",
  "lastName": "Anyalechi",
  "email": "chidiebere@updated.com",
  "favoriteColor": "Blue",
  "birthday": "1994-07-20"
}

### Delete contact
DELETE http://localhost:8080/contacts/68bc57dc92caf43538c1dc12
